[2025-03-24T09:42:26.643+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_fetch_url_csv.upload_2023_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [queued]>
[2025-03-24T09:42:26.655+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_fetch_url_csv.upload_2023_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [queued]>
[2025-03-24T09:42:26.656+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-03-24T09:42:26.686+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): upload_2023_W1_spring_Outer.csv> on 2025-03-24 09:42:22.627627+00:00
[2025-03-24T09:42:26.691+0000] {standard_task_runner.py:60} INFO - Started process 1794 to run task
[2025-03-24T09:42:26.697+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_fetch_url_csv', 'upload_2023_W1_spring_Outer.csv', 'manual__2025-03-24T09:42:22.627627+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/test_fetch_url_csv.py', '--cfg-path', '/tmp/tmp8fq0ulax']
[2025-03-24T09:42:26.702+0000] {standard_task_runner.py:88} INFO - Job 120: Subtask upload_2023_W1_spring_Outer.csv
[2025-03-24T09:42:26.767+0000] {task_command.py:423} INFO - Running <TaskInstance: test_fetch_url_csv.upload_2023_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [running]> on host 3d764bfd33f3
[2025-03-24T09:43:05.012+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_fetch_url_csv' AIRFLOW_CTX_TASK_ID='upload_2023_W1_spring_Outer.csv' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T09:42:22.627627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T09:42:22.627627+00:00'
[2025-03-24T09:46:15.374+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-24T09:46:15.439+0000] {process_utils.py:131} INFO - Sending 15 to group 1794. PIDs of all processes in the group: [1794]
[2025-03-24T09:46:15.441+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1794
[2025-03-24T09:46:15.454+0000] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-24T09:45:37.780+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1794, status='terminated', exitcode=0, started='09:42:26') (1794) terminated with exit code 0
