[2025-03-23T09:19:19.484+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_bq.load_csv_to_bq manual__2025-03-23T09:19:16.240743+00:00 [queued]>
[2025-03-23T09:19:19.496+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_bq.load_csv_to_bq manual__2025-03-23T09:19:16.240743+00:00 [queued]>
[2025-03-23T09:19:19.496+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-03-23T09:19:19.512+0000] {taskinstance.py:2214} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bq> on 2025-03-23 09:19:16.240743+00:00
[2025-03-23T09:19:19.517+0000] {standard_task_runner.py:60} INFO - Started process 2071 to run task
[2025-03-23T09:19:19.521+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_bq', 'load_csv_to_bq', 'manual__2025-03-23T09:19:16.240743+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/load_csv_to_bq.py', '--cfg-path', '/tmp/tmpn_5bnqx_']
[2025-03-23T09:19:19.523+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask load_csv_to_bq
[2025-03-23T09:19:19.602+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_bq.load_csv_to_bq manual__2025-03-23T09:19:16.240743+00:00 [running]> on host c0ff61c5806f
[2025-03-23T09:19:19.704+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_bq' AIRFLOW_CTX_TASK_ID='load_csv_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T09:19:16.240743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T09:19:16.240743+00:00'
[2025-03-23T09:19:19.722+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-23T09:19:19.731+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-23T09:19:19.734+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2025-03-23T09:19:19.807+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dtc-de-course-447820', 'datasetId': 'my_project_dataset', 'tableId': 'monitoring_locations'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://my-deproject-data-bucket/test_cycle/monitoring_locations.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'Site ID', 'type': 'STRING'}, {'name': 'Location description', 'type': 'STRING'}, {'name': 'Borough', 'type': 'STRING'}, {'name': 'Functional area for monitoring', 'type': 'STRING'}, {'name': 'Road type', 'type': 'STRING'}, {'name': 'Is it on the strategic CIO panel?', 'type': 'STRING'}, {'name': 'Old site ID (legacy)', 'type': 'STRING'}, {'name': 'Easting (UK Grid)', 'type': 'FLOAT'}, {'name': 'Northing (UK Grid)', 'type': 'FLOAT'}, {'name': 'Latitude', 'type': 'FLOAT'}, {'name': 'Longitude', 'type': 'FLOAT'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2025-03-23T09:19:19.809+0000] {bigquery.py:1612} INFO - Inserting job ***_load_csv_to_bq_load_csv_to_bq_2025_03_23T09_19_16_240743_00_00_45e7c92ed2dfb82863d386b75dc031ef
[2025-03-23T09:19:21.214+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 384, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 306, in _submit_job
    return hook.insert_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1615, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 827, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-447820/jobs?prettyPrint=false: Invalid field name "Is it on the strategic CIO panel?". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
[2025-03-23T09:19:21.229+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=load_csv_to_bq, task_id=load_csv_to_bq, execution_date=20250323T091916, start_date=20250323T091919, end_date=20250323T091921
[2025-03-23T09:19:21.248+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task load_csv_to_bq (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-447820/jobs?prettyPrint=false: Invalid field name "Is it on the strategic CIO panel?". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names; 2071)
[2025-03-23T09:19:21.285+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-23T09:19:21.310+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
