[2025-03-24T08:11:42.248+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: fetch_filtered_data_and_upload_to_gcs.download_and_upload_filtered_files manual__2025-03-24T08:11:39.116390+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
