[2025-03-24T09:42:26.620+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_fetch_url_csv.upload_2024_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [queued]>
[2025-03-24T09:42:26.632+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_fetch_url_csv.upload_2024_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [queued]>
[2025-03-24T09:42:26.633+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-03-24T09:42:26.653+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): upload_2024_W1_spring_Outer.csv> on 2025-03-24 09:42:22.627627+00:00
[2025-03-24T09:42:26.666+0000] {standard_task_runner.py:60} INFO - Started process 1793 to run task
[2025-03-24T09:42:26.681+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_fetch_url_csv', 'upload_2024_W1_spring_Outer.csv', 'manual__2025-03-24T09:42:22.627627+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/test_fetch_url_csv.py', '--cfg-path', '/tmp/tmpfsl9o8kr']
[2025-03-24T09:42:26.688+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask upload_2024_W1_spring_Outer.csv
[2025-03-24T09:42:26.757+0000] {task_command.py:423} INFO - Running <TaskInstance: test_fetch_url_csv.upload_2024_W1_spring_Outer.csv manual__2025-03-24T09:42:22.627627+00:00 [running]> on host 3d764bfd33f3
[2025-03-24T09:43:04.995+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_fetch_url_csv' AIRFLOW_CTX_TASK_ID='upload_2024_W1_spring_Outer.csv' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T09:42:22.627627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T09:42:22.627627+00:00'
[2025-03-24T09:46:15.422+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-24T09:46:15.488+0000] {process_utils.py:131} INFO - Sending 15 to group 1793. PIDs of all processes in the group: [1793]
[2025-03-24T09:46:15.490+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1793
[2025-03-24T09:46:15.502+0000] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-24T09:45:37.791+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1793, status='terminated', exitcode=0, started='09:42:26') (1793) terminated with exit code 0
